#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(dirname "${BASH_SOURCE}")"
source $SCRIPT_DIR/utils

setup_usage() {
  echo "usage: setup_raas setup [--overwrite]"
}

setup() {
  local overwrite=${1:-""}
  case ${overwrite} in
    "--overwrite"*)
      ;;
    "")
      ;;
    *)
      setup_usage
      exit 1
      ;;
  esac

  setup_raas_env # from hack/utils
  setup_dir ${RAAS_SECRETS_DIR} ${RAAS_SECRETS_REPO}
  setup_dir ${PKS_RELENG_CI_DIR} ${PKS_RELENG_CI_REPO}

  echo -n "Enter vault password:"
  read -s vault_password
  echo

  secret_files=("raas-credentials" "nsx-t-secrets" "pks-releng-write-locks-bot")
  iaas_secret_file="vsphere-nsx-variables"
  raas_variable_file="raas-variables"
  releng_profile_tag="releng"

  pushd ${RAAS_SECRETS_DIR} 2>&1 >/dev/null
    for f in "${secret_files[@]}"; do
      echo "adding ${f}"
      ct profile create --var-file=<(ansible-vault decrypt --vault-password-file <(echo "${vault_password}") --output - ${f}.yml) -n ${f} --tag ${releng_profile_tag} ${overwrite}
    done
  popd 2>&1 >/dev/null

  pushd ${PKS_RELENG_CI_DIR} 2>&1 >/dev/null
    echo "adding ${iaas_secret_file}"
    ct profile create --var-file="${iaas_secret_file}.yml" -n "${iaas_secret_file}" --tag ${releng_profile_tag} ${overwrite}

    # create raas-variables profile as a template profile so that each time you use it, you'll be asked
    # about values you want put in
    echo "adding ${raas_variable_file}"
    ct profile create --var-file=<(ct template convert -t <(sed '/^<%$/,/^%>$/d' ${raas_variable_file}.yml )) -n ${raas_variable_file} --tag ${releng_profile_tag}-template --template ${overwrite}
  popd 2>&1 >/dev/null

}

teardown() {
  unset_env # from hack/utils
  for f in "${secret_files[@]}"; do
    ct profile delete -n ${f}
  done
  ct profile delete -n ${iaas_secret_file}
  ct profile delete -n ${raas_variable_file}
}

usage() {
  echo "usage:"
  echo -e "\tsetup_raas setup"
  echo -e "\tsetup_raas teardown"
}

main() {
  if [ ${#@} -le 0 ]; then
    usage
    exit 1
  fi
  local subcmd=${1}
  shift
  case ${subcmd} in
    "setup"*)
      setup "$@"
      ;;
    "teardown"*)
      teardown "$@"
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

main "$@"
